### ISSUE TITLE
Derive macro parsing error on other derive macro attributes

### ISSUE THREAD

**Issue by BenHall-7** [jam1garner/binread#2] opened 2020-05-26 23:33 UTC
As the title states. For example, if I use an attribute for serde's derive macro, I get an error. Here's a minimal reproducible example:

```rust
use binread::BinRead;
use serde::{Serialize, Deserialize};

#[derive(BinRead, Serialize, Deserialize)]
pub struct MyType {
    #[serde(rename = "field")]
    pub my_field: u8
}
```

```
error: Cannot parse, expected one of the following: Big, Little, Default, Ignore, DerefNow, RestorePosition, PostProcessNow, Try, Map, ParseWith, Magic, Args, Assert, Calc, Count, IsLittle, IsBig, Offset, OffsetAfter, If, PadBefore, PadAfter, AlignBefore, AlignAfter, SeekBefore, PadSizeTo
 --> src\main.rs:6:13
  |
6 |     #[serde(rename = "field")]
  |             ^^^^^^
```

**Comment by jam1garner** [comment] 2020-06-15 15:56
In hindsight, this is a Duplicate of #1

**Closed by jam1garner** 2020-06-15 15:56 UTC
Labels: bug
